# Generated by Django 4.1.3 on 2023-06-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='유저아이디')),
                ('password', models.CharField(max_length=50, verbose_name='비밀번호')),
            ],
        ),
    ]
